# -*- coding: utf-8 -*-
"""PSML1i.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VE8LDv0t_kpHV8TDlrB4IvxxDqlQA9HR
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy import cov
from scipy.stats import pearsonr
import statistics

def leastsqr(x, y):
  x_square = [i**2 for i in x]
  b = (sum(y)*sum(x_square) - sum(x)*sum(np.multiply(x, y)))/(len(x)*sum(x_square)- sum(x)**2)
  m = (len(x)*sum(np.multiply(x, y)) - sum(x)*sum(y))/(len(x)*sum(x_square) - sum(x)**2)
  y_hat = [round(m*i+b, 2) for i in x]
  errors = y_hat-y
  lstsqr = (sum([i**2 for i in errors])/len(x))**0.5
  print(round(lstsqr ,2))

x = [2, 3, 5, 7, 9]
x1 = np.array(x)
y = [4, 5, 7, 10, 15]
y1 = np.array(y)
print("RMSE Val for predicted and current is : ")
leastsqr(x1, y1)
print("With Outliers introduced")
x.append(10)
y.append(25)
x2 = np.array(x)
y2 = np.array(y)
leastsqr(x2, y2)

#Covariance and Correlation
covariance = cov(x, y)
stdvx = statistics.stdev(x)
stdvy = statistics.stdev(y)
print("Covariance : ",covariance)
correlation = covariance/(stdvx*stdvy)
corr, _ = pearsonr(x, y)
print("Pearson's Correlation : " , corr)

#Box plot
data = [y1, y2]
fig = plt.figure(figsize= (10, 7))
ax = fig.add_axes([0, 0, 1, 1])
bp = ax.boxplot(data)
plt.show()